import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { verifyAppointmentToken } from "@/lib/appointment-token";

interface RouteContext {
  params: Promise<{ id: string }>;
}

/**
 * GET /api/appointments/[id]/confirm?token=<signed-token>
 *
 * Marks the appointment as CONFIRMED when a customer clicks the confirmation
 * link. Requires a valid HMAC token generated by generateAppointmentToken().
 * Returns JSON — callers may redirect the customer to the confirmation page
 * after a successful response.
 */
export async function GET(req: NextRequest, { params }: RouteContext) {
  const { id } = await params;
  const token = req.nextUrl.searchParams.get("token");

  if (!id) {
    return NextResponse.json(
      { error: "Missing appointment ID" },
      { status: 400 }
    );
  }

  if (!token) {
    return NextResponse.json(
      { error: "Missing token" },
      { status: 400 }
    );
  }

  if (!verifyAppointmentToken(id, "confirm", token)) {
    return NextResponse.json(
      { error: "Invalid or expired token" },
      { status: 403 }
    );
  }

  const appointment = await prisma.appointment.findUnique({
    where: { id },
    include: { business: { select: { phone: true, phoneNumber: true } } },
  });

  if (!appointment) {
    return NextResponse.json(
      { error: "Appointment not found" },
      { status: 404 }
    );
  }

  if (appointment.status === "CANCELLED") {
    return NextResponse.json(
      { error: "This appointment has been cancelled" },
      { status: 400 }
    );
  }

  // Idempotent — already confirmed
  if (appointment.status === "CONFIRMED") {
    return NextResponse.json({
      ok: true,
      appointmentId: appointment.id,
      status: appointment.status,
      confirmedAt: appointment.confirmedAt,
    });
  }

  const updated = await prisma.appointment.update({
    where: { id },
    data: {
      status: "CONFIRMED",
      confirmedAt: new Date(),
    },
  });

  // Notify the salon owner via SMS if possible
  if (
    appointment.business.phone &&
    appointment.business.phoneNumber
  ) {
    try {
      const [{ sendSms }, { formatDateTime }] = await Promise.all([
        import("@/lib/sms"),
        import("@/lib/utils"),
      ]);

      const fromNumber =
        process.env.TWILIO_PHONE_NUMBER ||
        appointment.business.phoneNumber.number;

      await sendSms(
        appointment.business.phone,
        `[RingPaw] ${appointment.customerName} confirmed their ${
          appointment.serviceName ?? "grooming"
        } appointment (${formatDateTime(appointment.startTime)}).`,
        fromNumber
      );
    } catch {
      // Non-fatal — log but do not fail the confirmation
      console.error("[confirm] Failed to send owner SMS notification");
    }
  }

  return NextResponse.json({
    ok: true,
    appointmentId: updated.id,
    status: updated.status,
    confirmedAt: updated.confirmedAt,
  });
}
